version: "1"
services:
 application:
    image: ${IMAGE_NAME}
    container_name: AmazonListingFiles
    ports: 
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - MONGO_DB_URL=${MONGO_DB_URL}
